<?php
    session_start();
    require 'API/db.php';
    $full_name = "";
    $email = "";
    $mobile = "";
    $password = "";
    $user_exists = "";

    function test_input($data) {
        $data = trim($data);
        $data = stripslashes($data);
        $data = htmlspecialchars($data);
        return $data;
    }
?>
<?php
    if (isset($_POST['action'])){

        // Storing inputs of form into php variable

        $full_name = test_input($_POST['full_name']);
        $email = test_input($_POST['email']);
        $mobile = test_input($_POST['mobile']);
        $password = password_hash($_POST['password'], PASSWORD_DEFAULT);


        $status=0;
        $activationcode=md5($email.time());
        // Checking user already exists or not

        $sql = "select email from sign_up where email = ?";
        $stmt = $conn->prepare($sql);
        $stmt->bind_param("s",$email);
        $stmt->execute();
        $result = $stmt->get_result();

        if ($result->num_rows > 0){
            $user_exists = "Email already exists!!";
        } elseif ($result->num_rows == 0){  // Adding New User into database
            $sql = "insert into sign_up (full_name,email,mobile_number,password,activationcode,status) values ('$full_name','$email','$mobile','$password','$activationcode','$status')";
            $result = $conn->query($sql);
            if ($result){
                require 'API/phpmailer/class.smtp.php';
                require 'API/phpmailer/PHPMailerAutoload.php';

                $mail = new PHPMailer();
                $mail->setFrom('admin@example.com');
                $mail->addAddress($email);
                $mail->Subject = "Email Verification Code MITAOE Placement Cell";
                $mail->Body = "
                <html></body><div><div>Dear $name,</div></br></br>
                <div style='padding-top:8px;'>Please click The following link For verifying and activation of your account</div>
                <div style='padding-top:10px;'><a href='http://localhost/Web/Placement_project/Placement_Project/email_signup_verification.php?code=$activationcode'>Click Here</a></div>
                <div style='padding-top:4px;'>
                Thanks Regards,
                MITAOE Placement Cell
                </div></div>
                </body></html>
                ";

                $mail->isHTML(true);
                $mail->AltBody = "This message is generated by plain text !";
                $mail->IsSMTP();
                $mail->SMTPSecure = 'ssl';
                $mail->Host = 'ssl://smtp.gmail.com';
                $mail->SMTPAuth = true;
                $mail->Port = 465;
                $mail->Username = 'pandavshyam@gmail.com';
                $mail->Password = 'Shyam@1998';
                if(!$mail->send()) {
                    echo 'Email is not sent.';
                } else {
                    echo 'Email has been sent.';
                }

                $user_exists = "Registration Successfull. Please login to continue";
                $_SESSION['msg'] = $user_exists;
                header("refresh:0;url=login.php");
            } else {
                $user_exists = "Sorry, something happend try after some time";
            }
        } else {
            $user_exists = "Sorry, something happend try after some time";
        }
    }
?>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up</title>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">

</head>
<style>
    body {
        overflow: hidden;
    }
    
    header {
        border-radius: 400px;
    }
    
    .p {
        width: 100%;
        display: grid;
        grid-template-columns: auto auto;
    }
    
    .itm1 {
        width: 100%;
        background: #94bbe9;
        height: 740px;
    }
    
    .itm2 {
        width: 100%;
    }
    
    .card {
        height: 500px;
    }
    
    .pp {
        width: 400px;
        /* border: 2px solid black; */
        height: 200px;
        margin-left: 160px;
        margin-top: 30px;
    }
    
    .g {
        width: 100%;
    }
    
    .g img {
        width: 500px;
        height: 100%;
    }
    
    @media screen and (max-width: 670px) {
        .itm1 {
            display: none;
        }
        .pp {
            margin-left: 60px;
            width: 100%;
        }
    }
</style>

<body>
    <div class="p">
        <div class="itm1">
            <div class="g">
            <div class="g">
                <br><br><br><br><br>
                <center><img src="public/img/sign_up.svg" alt=""></center>
            </div>
            </div>
        </div>
        <div class="itm2">
            <div class="cc">
                <div class="pp">
                    <center>
                        <h3>Signup</h3>
                    
                        <b style="color: red;"><?php echo $user_exists;?></b>
                    </center>
                    <div class="form">
                        <form action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>" onsubmit="return validate();" method="POST">

                            <div class="input-field">
                                <i class="material-icons prefix">account_circle</i>
                                <input id="full_name" type="text" name="full_name" class="validate" required value="<?php echo $full_name;?>">
                                <label for="full_name">Full Name</label>
                            </div>

                            <div class="input-field">
                                <i class="material-icons prefix">email</i>
                                <input id="email" name="email" type="text" class="validate" required value="<?php echo $email;?>">
                                <label for="email">Email</label>
                            </div>

                            <div class="input-field">
                                <i class="material-icons prefix">phone</i>
                                <input id="mobile" name="mobile" maxlength="12" pattern="[7-9]{1}[0-9]{9}" type="text" class="validate" required value="<?php echo $mobile;?>">
                                <label for="mobile">Mobile Number</label>
                            </div>

                            <div class="input-field">
                                <i class="material-icons prefix">lock</i>
                                <input id="password" name="password" type="password" class="validate" required>
                                <label for="password">Password</label>
                            </div>

                            <div class="input-field">
                                <i class="material-icons prefix">lock</i>
                                <input id="confirm_password" name="confirm_password" type="password" class="validate" required>
                                <label for="confirm_password">Confirm Password</label>
                            </div>
                            <p>
                                <label>
                                    <input type="checkbox" onclick="myFunction()" />
                                    <span>Show Password</span>
                                </label>
                            </p>
                            <center>
                                <button type="submit" class="btn waves-effect waves-light blue darken-1"   id="submit" name="action">Signup
                                    <i class="material-icons right">send</i>
                                </button>
                            </center>
                            <br><br>
                            <center>Have an Account? <a href="login.php">Login</a></center>
                            <hr>
                            <center><img height="30px" src="public/img/google.png" alt=""> &nbsp;&nbsp;&nbsp;
                                <img height="40px;" src="public/img/twitter.jpg" alt=""> &nbsp;
                            </center>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        function myFunction() {
            var x = document.getElementById("password");
            var y = document.getElementById("confirm_password");


            if (x.type === "password") {
                x.type = "text";
            } else {
                x.type = "password";
            }


            if (y.type === "password") {
                y.type = "text";
            } else {
                y.type = "password";
            }
        }

        function validate(){
         var x = document.getElementById("password").value;
         var y = document.getElementById("confirm_password").value;
         if(x != y){
            alert("Password Dosen't Match Please try again");
            return false;
           }
        }
    </script>

    <!-- Jquery Library -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

    <!-- Compiled and minified JavaScript -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>

</html>
<?php $conn->close();?>

