<?php
require 'API/phpmailer/class.smtp.php';
require 'API/phpmailer/PHPMailerAutoload.php';

$mail = new PHPMailer();
$mail->setFrom('admin@example.com');
$mail->addAddress('shyampandav@gmail.com');
$mail->Subject = 'Message sent by PHPMailer';
$mail->Body = '<h2>Hello!</h2><p style="color:Blue;">
I am using PHPMailer to send email</p>';

$mail->isHTML(true);
$mail->AltBody = "This message is generated by plain text !";
$mail->IsSMTP();
$mail->SMTPSecure = 'ssl';
$mail->Host = 'ssl://smtp.gmail.com';
$mail->SMTPAuth = true;
$mail->Port = 465;
$mail->Username = 'pandavshyam@gmail.com';
$mail->Password = 'Shyam@1998';
if(!$mail->send()) {
  echo 'Email is not sent.';
  echo 'Email error: ' . $mail->ErrorInfo;
} else {
  echo 'Email has been sent.';
}
?>